// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvekIT9W7eAwLJizKI07grrXHB6kzwnc0',
    appId: '1:351248071207:web:600f5e4b30e8874f08ec02',
    messagingSenderId: '351248071207',
    projectId: 'spotifyj21062001',
    authDomain: 'spotifyj21062001.firebaseapp.com',
    storageBucket: 'spotifyj21062001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHMiIzHEfUDUIpXX5RzQZcu7krLVqtDE',
    appId: '1:351248071207:android:8d5336ca6e93d7ed08ec02',
    messagingSenderId: '351248071207',
    projectId: 'spotifyj21062001',
    storageBucket: 'spotifyj21062001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVghLznlZt6-cgYDw6u3kSxKy6PsTZ3lQ',
    appId: '1:351248071207:ios:58563b3f03c8801808ec02',
    messagingSenderId: '351248071207',
    projectId: 'spotifyj21062001',
    storageBucket: 'spotifyj21062001.appspot.com',
    iosBundleId: 'com.example.spotifyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVghLznlZt6-cgYDw6u3kSxKy6PsTZ3lQ',
    appId: '1:351248071207:ios:58563b3f03c8801808ec02',
    messagingSenderId: '351248071207',
    projectId: 'spotifyj21062001',
    storageBucket: 'spotifyj21062001.appspot.com',
    iosBundleId: 'com.example.spotifyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvekIT9W7eAwLJizKI07grrXHB6kzwnc0',
    appId: '1:351248071207:web:f0184d3382a1472508ec02',
    messagingSenderId: '351248071207',
    projectId: 'spotifyj21062001',
    authDomain: 'spotifyj21062001.firebaseapp.com',
    storageBucket: 'spotifyj21062001.appspot.com',
  );

}